Added Wayland support and fixed auto-update scripts
flathub/me.hyliu.fluentreader pull request #33
Opened 2023-03-25 23:20 UTC by danilown

Added Wayland support by including the correct `ozone-platform` and fixed auto-update scripts using the newest version from `flatpak-node-generator`.

2023-03-26 02:49 UTC, cognition9144 requested changes
Thank you for your contribution

2023-03-26 02:49 UTC, cognition9144 commented on me.hyliu.fluentreader.yml
> +  - --socket=x11
```suggestion
```

2023-03-26 02:49 UTC, cognition9144 commented on update.py
> +    cache_dir = ".cache"
Any reason to change this?

2023-03-26 02:55 UTC, cognition9144 commented on update.sh
> +rm -rf ./.cache
Not a requirement, but it would be nice if you could make it a github action, like https://github.com/flathub/com.logseq.Logseq/blob/master/.github/workflows/update.yml

2023-03-26 11:20 UTC, danilown commented on update.py
> +    cache_dir = ".cache"
That's just when executing the  `update.sh`  script locally (i.e. local builds). It makes everything "in place", as now installing the `flatpak-node-generator` is required and it is also installed in the `./.cache` directory.

2023-03-26 11:29 UTC, danilown commented on update.sh
> +rm -rf ./.cache
Yeah, that would be cool. I'll take a look at it.

2023-03-28 09:05 UTC, proletarius101 approved these changes

2023-03-28 09:07 UTC, cognition9144 approved these changes

2023-03-28 09:08 UTC, merged